sonar.projectKey=senad-d_DrawMe
sonar.organization=senad-d

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=assets/**,example/**,img/**,scripts/**,coverage/**
sonar.coverage.exclusions=tests/**,scripts/**,vitest.config.ts,eslint.config.js
